### ISSUE TITLE
Hyperparameter setting

### ISSUE THREAD

**Issue by bamiikim** [kaist-dmlab/RECURVE#10]
Thanks for the great work. Do various hyperparameters, such as window size or the window for curvature measurement, need to be adjusted depending on different datasets? Is there a way to determine the optimal settings based on the characteristics of the data?

**Comment by Cabbalett** [comment]
I would say that the precise value optimal hyperparameter will depend on the domain/characteristic of the data. I suggest starting with {50,100} for the window size, as mentioned in our paper.
