### ISSUE TITLE
Dataset Download Instructions

### ISSUE THREAD

**Issue by ddoyoungkim** [kaist-dmlab/RECURVE#13]
For the used dataset e.g. 50salads, the README simply mentions a URL for downloading but does not provide the actual link. Additionally, there are no instructions on how to organize this dataset within the /dataset directory.

**Comment by Cabbalett** [comment]
Sorry for the confusion. After you download the dataset, executing `dataset/preprocessing.ipynb` will automatically organize the dataset into the desired format. Thank you.
